apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ftp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ftp
  template:
    metadata:
      labels:
        app: my-ftp
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: "portal-minecraft"
      containers:
        - name: my-ftp-container
          image: tbwlat/vsftpd:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 21
              protocol: TCP
              name: "ftp-server"
          volumeMounts:
            - mountPath: "/data"
              name: task-pv-storage
          env:
            - name: FTP_USER
              valueFrom:
                secretKeyRef:
                  name: ftpsecret
                  key: ftpuser
            - name: FTP_PASS
              valueFrom:
                secretKeyRef:
                  name: ftpsecret
                  key: ftppassword
            - name: PASV_ADDRESS
              value: 169.57.112.146
            - name: PASV_MIN_PORT
              value: "31100"
            - name: PASV_MAX_PORT
              value: "31101"
