apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  selector:
    matchLabels:
      app: minecraft
      appid: portal