apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-srv
spec:
  selector:
    matchLabels:
      app: mc-srv
  template:
    metadata:
      name: mc-srv
      labels:
        app: mc-srv
    spec:
      containers:
        - name: mc-srv
          image: "itzg/minecraft-server"
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: TYPE
              value: "SPIGOT"
            - name: VERSION
              value: "1.14.4"
            - name: MEMORY
              value: "1G"
          ports:
            - containerPort: 25565
          tty: true
          stdin: true
          volumeMounts:
            - name: minecraftdata
              mountPath: /data
      volumes:
        - name: minecraftdata
          persistentVolumeClaim:
            claimName: portal-minecraft
---
apiVersion: v1
kind: Service
metadata:
  name: mc-srv-service
  labels:
    app: mc-srv
spec:
  type: NodePort
  selector:
    app: mc-srv
  ports:
   - protocol: TCP
     port: 25565
     nodePort: 30072
